//
//  ViewController.swift
//  LoaderSandbox
//
//  Created by Sergey Petrachkov on 02/12/2021.
//

import UIKit
import ImagesLoaderSandbox
import Combine

class ViewController: UIViewController {

    lazy var button: UIButton = {

        let button = UIButton(type: .custom)
        button.setTitle("Tap me", for: .normal)
        self.view.addSubview(button)
        button.translatesAutoresizingMaskIntoConstraints = false
        button.centerXAnchor.constraint(equalTo: self.view.centerXAnchor).isActive = true
        button.centerYAnchor.constraint(equalTo: self.view.centerYAnchor).isActive = true
        button.widthAnchor.constraint(equalToConstant: 100).isActive = true
        button.heightAnchor.constraint(equalToConstant: 100).isActive = true


        button.backgroundColor = .blue
        return button
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        button.addTarget(self, action: #selector(self.didTap), for: .touchUpInside)
    }

    @objc
    private func didTap() {
        let anotherVC = AnotherVC()
        present(anotherVC, animated: true)
    }

}

class AnotherVC: UIViewController {

    let loader = SyncImagesLoader()
    var disposableBag = Set<AnyCancellable>()
    lazy var button: UIButton = {

        let button = UIButton(type: .custom)
        self.view.addSubview(button)
        button.translatesAutoresizingMaskIntoConstraints = false
        button.widthAnchor.constraint(equalToConstant: 100).isActive = true
        button.heightAnchor.constraint(equalToConstant: 100).isActive = true
        button.centerXAnchor.constraint(equalTo: self.view.centerXAnchor).isActive = true
        button.centerYAnchor.constraint(equalTo: self.view.centerYAnchor).isActive = true
        button.backgroundColor = .blue
        return button
    }()

    lazy var label: UILabel = {

        let button = UILabel(frame: .zero)
        self.view.addSubview(button)
        button.translatesAutoresizingMaskIntoConstraints = false
        button.widthAnchor.constraint(equalToConstant: 300).isActive = true
        button.heightAnchor.constraint(equalToConstant: 100).isActive = true
        button.centerXAnchor.constraint(equalTo: self.view.centerXAnchor).isActive = true
        button.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        return button
    }()


    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        label.text = "Initial"
        button.addTarget(self, action: #selector(self.didTap), for: .touchUpInside)
    }

    deinit {
        print("\(self) deinit")
    }


    @objc
    private func didTap() {
        let images = [
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/130.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/230.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/300.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/1234.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/2000.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://via.placeholder.com/3999.png")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://i.pinimg.com/originals/41/9c/e0/419ce0d1dcdeee9b41436a10288cd709.jpg")!),
            CacheImageSyncRequest(key: UUID().uuidString, url: URL(string: "https://pixabay.com/get/g249565b858e1ff8b283ca3f307eab145ee41f862cb5998f9f43bcfc5769a173d0b835b90f19b558c94e42606a23735a7_1280.jpg")!),

        ]
        loader.progressCallback = { [weak self] progress, current, total in
            self?.label.text = "\(progress * 100)% \(current)/\(total)"
        }
        loader.cacheFunction = { _, key in
            print("cache with \(key)")
        }
            loader
                .fetchImages(resources: images)
                .sink(receiveCompletion: { [weak self] _ in
                    print("It's over")
                    self?.label.text = "It's over"
                }, receiveValue: { result in
                    print("sink --> \(result)")
                })
                .store(in: &disposableBag)
    }
}

